### ISSUE TITLE
VoCore2

### ISSUE THREAD

**Issue by alick** [tuna/collection#109]
看下这个怎样？

硬币大小一块小板，Lite 版只需 4 刀。可做无线路由器/NAS/音乐服务器等。软硬件全开源。

https://www.indiegogo.com/projects/vocore2-4-coin-sized-linux-computer-with-wifi#/

**Comment by pandada8** [comment]
openwrt 不清真（
mtk 不清真（

**Comment by scateu** [comment]
所以现在路由器上用啥比较好？

**Comment by gaoyichuan** [comment]
这种东西都烂大街了吧。。

**Comment by sztsian** [comment]
达到可用状态需要的总价格并不理想。还不如直接一片Orange Pi Zero呢，arm+Linux足够清真

**Comment by huiyiqun** [comment]
OpenWRT确实比较麻烦

2016-11-07 13:13 GMT+08:00 Zamir SUN <notifications@github.com>:

**Comment by sakamoto-poteko** [comment]
> 所以现在路由器上用啥比较好？

FreeBSD吧

ipf和ipnat还挺好使的

**Comment by sztsian** [comment]
四年过去了，随着各种灵车的泛滥， VoCore2 已经不香了。
这帖子关了吧？

**Comment by xiaoxiangmoe** [comment]
@sztsian 什么是灵车泛滥？
