### ISSUE TITLE
此标准发布即日起不执行。

### ISSUE THREAD

**Issue by lizr2004** [tuna/collection#141]
<article>
							<div class="head" id="april-fools-day">
								<h3># 我们做出了一个艰难的决定</h3>
							</div>
							<div class="meta">
								<span class="fa fa-calendar"></span> 2017-04-01 <span class="fa fa-user" style="margin-left: 1em"> TUNA 镜像站全体运维人员</span>
							</div>
							<div class="content"><p>由于 TUNA 镜像站经营不善，团长带着女朋友跑了，整个组织濒临破产边缘。经第一届金枪鱼全体代表大会讨论研究决定，TUNA 名下的 Telegram 群组和镜像站将启用免费使用+付费增值模式。具体收费标准如下：</p>

<table class="table">
  <thead>
    <tr>
      <th>项目</th>
      <th>会员</th>
      <th>黄金会员</th>
      <th>钻石会员</th>
      <th>SVIP</th>
      <th>备注</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>收费标准</td>
      <td>免费</td>
      <td>15元/月 <strong>¥179/年</strong></td>
      <td>30元/月 <strong>¥359/年</strong></td>
      <td>50元/月 <strong>¥599/年</strong></td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>Telegram 发言</td>
      <td>5条/周</td>
      <td>30条/周</td>
      <td>90条/周</td>
      <td><strong>无限</strong></td>
      <td>超出部分 1元/条</td>
    </tr>
    <tr>
      <td>Telegram 发言置顶</td>
      <td>无</td>
      <td>1条/月</td>
      <td>3条/月</td>
      <td><strong>10条/月</strong></td>
      <td>超出部分 10元/条</td>
    </tr>
    <tr>
      <td>镜像源限速</td>
      <td>100KB/s</td>
      <td>1MB/s</td>
      <td>5MB/s</td>
      <td><strong>不限速</strong></td>
      <td>需使用专用包管理器<code class="highlighter-rouge">tuna-get</code>，<code class="highlighter-rouge">apt-get</code>等官方包管理器限速100KB/s</td>
    </tr>
    <tr>
      <td>包管理器去广告</td>
      <td>无</td>
      <td>5s后可跳过</td>
      <td>可跳过</td>
      <td><strong>无广告</strong></td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>其它特权</td>
      <td>无</td>
      <td>无</td>
      <td><strong>Telegram群红名</strong></td>
      <td><strong>上线提醒</strong></td>
      <td>&nbsp;</td>
    </tr>
  </tbody>
</table>

<p>此标准发布即日起不执行。</p>
</div>
						</article>

**Comment by xavieryao** [comment]
Duplicated with https://github.com/tuna/collection/issues/104
