### ISSUE TITLE
bug:无法正确访问段子: https://duanzi.tuna.moe/



### ISSUE THREAD

**Issue by lavacup2233** [tuna/collection#197]
会被重定向至:
[https://www.educlub.com.br/](https://www.educlub.com.br/)

**Comment by ZenithalHourlyRate** [comment]
感谢您发现该问题，您所说的重定向无法复现。

目前 duanzi.tuna.moe 指向的服务器已经停止维护，我在最近的 [commit](https://github.com/tuna/collection/commit/baec8b789c781d195f850898f04cac4670ce45ed) 中移除了该链接。
