### ISSUE TITLE
npm的镜像需求请求

### ISSUE THREAD

**Issue by StevenGardnerGMJ** [tuna/collection#202]
尊敬的tuna：
十分感谢提供的镜像方法为我解决了许多工作上的需求。
另外我找了一下镜像站 没发现有npm的镜像，
尊敬的诸位大佬，有兴趣加入npm镜像源吗，
在此跪谢。

**Comment by xiashali** [comment]
发错 repo 了

**Comment by xiashali** [comment]
https://github.com/tuna/issues/issues/290
