### ISSUE TITLE
创建社区软件包 fortunes-tuna fortunes-xdl

### ISSUE THREAD

**Issue by CDLuminate** [tuna/collection#6]
收集段子这项光荣的任务就交给你了。

**Comment by CDLuminate** [comment]
只要能提供一个平文本，我就能把Debian/Ubuntu/Mint/Deepin/Kali/...  (此处省略100种发行版) 包做好。

**Comment by huiyiqun** [comment]
Arch~

**Comment by CDLuminate** [comment]
@huiyiqun  Arch包交给B哥好了

**Comment by CDLuminate** [comment]
Github如果有API可以把issues及其内容扒下来的话，真的可以写脚本自动生成社区fortunes包。

**Comment by huiyiqun** [comment]
https://developer.github.com/v3/issues/ 有啊

**Comment by huiyiqun** [comment]
```
curl https://api.github.com/repos/tuna/collection/issues
```

**Comment by CDLuminate** [comment]
@huiyiqun That's super awesome, I'm hacking on it.

**Comment by CDLuminate** [comment]
让您的fortune充满社区情怀。

```
#!/usr/bin/sh
set -e
# Fortune cookie generator for TUNA DuanZi
#   https://github.com/tuna/collection
# Copyright © 2016 Zhou Mo <cdluminate@gmail.com>
# MIT/Expat License

# pull github issues
curl -s https://api.github.com/repos/tuna/collection/issues > issues

# parse issues and generate fortunes plain text
python3 -c "
import json
issues = json.loads(open('issues','r').read())
assert(isinstance(issues, list))
print('Found {} DuanZi.'.format(len(issues)))
with open('tunaduanzi','w+') as f:
  for issue in issues:
    if 'title' in issue: f.write('«{}»\n\n'.format(issue['title'].replace('%','')))
    if 'body'  in issue: f.write('{}'.format(issue['body'].replace('%','')))
    f.write('\n%\n')
"

# generate the fortune format cookie file
strfile tunaduanzi

# install, requires root permission
[ -e tunaduanzi.dat ] && sudo install -m0755 tunaduanzi.dat /usr/share/games/fortunes/

# smoke test
fortune tunaduanzi
```

**Comment by CDLuminate** [comment]
@huiyiqun @bigeagle  目前的问题是，单次curl请求只能扒30个段子。不过上边的脚本已经可以用。

**Comment by CDLuminate** [comment]
要不要我把这个写成Makefile，提一个PR，这样的话贵社区的段子们就可以安装成fortune cookie来用了

**Comment by CDLuminate** [comment]
自己挖的坑跪着也要填上。

TUNA duanzi 部分节选已经导入fortune-zh 2.4版本中。预览版本可以在此下载：

http://debomatic-amd64.debian.net/distribution#unstable/fortune-zh/2.4/buildlog
（该链接可能半个月左右后失效）

稍后上传至Debian unstable。

**Comment by CDLuminate** [comment]
Marking this issue as done.

**Comment by scateu** [comment]
哇好棒!

以及我土了第一次知道有fortune这么好玩的东西...

--
Wang Kang
Email: scateu@gmail.com
Blog: http://scateu.me
Fingerprint: 011F 0492 97D6 5D75 8AC4  6458 D43F 3CE2 3353 B7BD
HAM Callsign: BH1RLW



On Sat, Jul 1, 2017, at 23:23, L. Zhou wrote:
> 自己挖的坑跪着也要填上。


> TUNA duanzi 部分节选已经导入fortune-zh 2.4版本中。预览版本可以在此下载：


> http://debomatic-amd64.debian.net/distribution#unstable/fortune-zh/2.4/buildlog>  （该链接可能半个月左右后失效）


> 稍后上传至Debian unstable。


> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].> 


Links:

  1. https://github.com/tuna/collection/issues/6#issuecomment-312438065
