### ISSUE TITLE
成为 Arch Linux 的 Tier 1 mirror

### ISSUE THREAD

**Issue by bigeagle** [tuna/collection#63]
We're currently Tier 2 mirror. If we managed to be Tier 1, we'd be the first Tier 1 mirror of mainland China, and get instant syncing from Arch Tier 0 rsync site.

**Tier 2 requirements**
- Disk-space >= 60 GB
- Sync off a tier 1 mirror (see https://archlinux.org/mirrors)
- Sync all contents of the upstream mirror (i.e. do not sync only some repositories)
- Do not sync more often than every hour, but you should sync at least once a day
- Sync on a random minute so it is more likely the requests will be spaced out with other mirrors
- Use the following rsync options: -rtlvH --delete-after --delay-updates --safe-links
- If you ever whish to send downtime notifications to our users, please use the arch-mirrors-announce list. You do not need to subscribe to be able to post.
- http support

**Tier 1 requirements**
- Tier 2 requirements
- Bandwidth >= 100Mbit/s
- rsync support
- Proven reliability (be a tier 2 mirror for a while and have reasonable uptime, response to out-of-sync notifications etc.)

**Comment by gaoyichuan** [comment]
看上去对TUNA来说毫无压力啊

**Comment by gaoyichuan** [comment]
Done
