### ISSUE TITLE
TUNA出游

### ISSUE THREAD

**Issue by bigeagle** [tuna/collection#82]
foxfin: 为什么TUNA不组织一些出去玩的活动呢？
xavier: 对啊对啊，比如说出去爬山什么的……
大鹰：这个啊，让我想到四月有个套路很深的番，叫迷家。剧情就是一堆人坐车去山里玩，这个番的海报是这样的。

![第一张](https://cloud.githubusercontent.com/assets/548512/15640965/da781920-266f-11e6-8bf5-4778a2740198.jpg)
![第二张](https://cloud.githubusercontent.com/assets/548512/15640974/ec62266c-266f-11e6-99b0-d53a6cfb9f6e.jpg)
![第三张](https://cloud.githubusercontent.com/assets/548512/15640953/ced8ec3e-266f-11e6-9c63-035d08de1668.jpg)
![第四张](https://cloud.githubusercontent.com/assets/548512/15640977/f69f99fc-266f-11e6-9290-e98322df8265.jpg)

大鹰：你们看，人越来越少，你们懂了吧？

xavier: **哦！我懂了，这就跟TUNA一样，招新完人好多，然后越来越少！**

**Comment by yangsheng6810** [comment]
然而据说人实际上几乎一个没少…

bigeagle <notifications@github.com>于2016年5月30日周一 02:11写道：

**Comment by bigeagle** [comment]
对啊！TUNA人也一个没少啊

**Comment by yangsheng6810** [comment]
//然而，或者说恰好，里面的人精神都不是很正常……

bigeagle <notifications@github.com>于2016年5月30日周一 02:13写道：

**Comment by pandada8** [comment]
![image](https://cloud.githubusercontent.com/assets/3305174/24609632/159be686-18ae-11e7-86f3-fcf611ec444a.png)

**Comment by huiyiqun** [comment]
药丸

**Comment by Harry-Chen** [comment]
Flag 今年去凤凰岭的时候被拔了！十一再去深圳玩！

**Comment by xavieryao** [comment]
那也别close啊

________________________________

**Comment by nicholascw** [comment]
> Miao Wang, [29.05.19 10:24]
> https://youtu.be/i4BLn84BAgE
>
> Miao Wang, [29.05.19 10:24]
> 嘻，今天去山水画廊开车去了
> 
> Miao Wang, [29.05.19 10:24]
> 录了段 vlog
>
> Miao Wang, [29.05.19 10:25]
> @xavieryao 老司机带路！
> 
> Jason Lau, [29.05.19 15:15]
> 坏人是不乱变道的好孩子
> 
> Peiran Yao, [29.05.19 18:43]
> [回复 Jason Lau]
> 我喜欢坏人的风格

**Comment by sztsian** [comment]
这 vlog 很 log

**Comment by scateu** [comment]
赞vlog  看完它感觉都要学会自动驾驶了
